// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQ-lhJcMiiex8KgMsUrq4AXtNaO9IZTOQ',
    appId: '1:593344548472:web:aa4af84055b8f22568e78d',
    messagingSenderId: '593344548472',
    projectId: 'ativedoss',
    authDomain: 'ativedoss.firebaseapp.com',
    databaseURL: 'https://ativedoss-default-rtdb.firebaseio.com',
    storageBucket: 'ativedoss.appspot.com',
    measurementId: 'G-MPBMTTWXC6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIa_q5dgxEs2porQB-wIjXD8lQVN_zajU',
    appId: '1:593344548472:android:5f93b2b704ab1aab68e78d',
    messagingSenderId: '593344548472',
    projectId: 'ativedoss',
    databaseURL: 'https://ativedoss-default-rtdb.firebaseio.com',
    storageBucket: 'ativedoss.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe4iHSe0RGIC4lQRYzT8SkK_JKyAIeN9c',
    appId: '1:593344548472:ios:507756a3e647049f68e78d',
    messagingSenderId: '593344548472',
    projectId: 'ativedoss',
    databaseURL: 'https://ativedoss-default-rtdb.firebaseio.com',
    storageBucket: 'ativedoss.appspot.com',
    iosClientId: '593344548472-0i3msahsln6l24i8imc3binu8mgjesdn.apps.googleusercontent.com',
    iosBundleId: 'com.example.converteArt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBe4iHSe0RGIC4lQRYzT8SkK_JKyAIeN9c',
    appId: '1:593344548472:ios:507756a3e647049f68e78d',
    messagingSenderId: '593344548472',
    projectId: 'ativedoss',
    databaseURL: 'https://ativedoss-default-rtdb.firebaseio.com',
    storageBucket: 'ativedoss.appspot.com',
    iosClientId: '593344548472-0i3msahsln6l24i8imc3binu8mgjesdn.apps.googleusercontent.com',
    iosBundleId: 'com.example.converteArt',
  );
}
